### ISSUE TITLE
Introduce versioning for janus, janus plugins

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1006]
Continuation of #951 

Make sure correct versioning is used, e.g. https://github.com/cargomedia/puppet-packages/pull/951/files#diff-185b5f15d1ada2040a101f460cf852e1R9 does not

Use the new [`git::repository` resource](https://github.com/cargomedia/puppet-packages/pull/1003)

**Comment by njam** [comment]
Duplicate of https://github.com/cargomedia/puppet-packages/issues/999 ?
