### ISSUE TITLE
Abstraction for service to be init-agnostic

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1017]
With the move to Ubuntu Vivid (and Debian Jessie at some point) systemd will become the default init..

Some work done in https://github.com/cargomedia/puppet-packages-ubuntu/pull/8

Ideally, modules using this define would not need know about the underlying init system. Not sure how far we might get

**Comment by njam** [comment]
done in https://github.com/cargomedia/puppet-packages/pull/1027
