### ISSUE TITLE
"cm_janus::proxy" should also include HTTP API?

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#1036]
So that the API can be served on http**s**, which is *secure* (API secret, data etc).

@tomaszdurka wdyt?
cc @kris-lab

**Comment by tomaszdurka** [comment]
I don't see a reason to expose janus-http.
If we want yes we can.

**Comment by njam** [comment]
It's just easier over the public Internet, using the normal DNS names.
Alternative would be to use some internal DNS (/etc/hosts?), which we don't currently have.
wdyt?

**Comment by tomaszdurka** [comment]
We are using private ips for all our other internal services. Why change for this one? :)
For me less open/public points = better. I would be up for internal dns, but it's a project.

**Comment by ppp0** [comment]
DNS can resolve to private addresses, fyi!

e.g.

`janus.foo.cargmedia.net  IN A 172.20.10.99`

**Comment by njam** [comment]
Agree, but we'd need to manage it - maybe use AWS API?

**Comment by njam** [comment]
CLosing in favor of https://github.com/cargomedia/puppet-cargomedia/pull/962
