### ISSUE TITLE
Puppet 3.8 doesn't work with systemd's "sysvinit compatibility layer"

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#1070]
Some of our services are using sysvinit-style scripts, which is supported by **systemd's sysvinit compatibility layer**. E.g. postfix, ntp, monit.

Unfortunately puppet's `Service` type only supports this scenario correctly in version 4 (see https://github.com/cargomedia/puppet-packages/pull/1068).

As an effect the `enabled?` check currently returns `false` although the service is enabled, and every puppet run will re-enable it.

cc @kris-lab @tomaszdurka @ppp0

**Comment by tomaszdurka** [comment]
Solution? use Daemon..?

**Comment by njam** [comment]
Either fully use systemd (or daemon), or upgrade to puppet 4…
