### ISSUE TITLE
Add init-agnostic logging

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1078]
Cf https://github.com/cargomedia/puppet-packages/pull/1076#issuecomment-165193695

In `systemd` this is a minor issue (`journalctl` and copying everything to `syslog`). Still, it would be cool to define a custom log file (may be not needed?)

ALso, consider logrotate (in `systemd` also batteries incl. ?)

**Comment by njam** [comment]
Can it be done with `start-stop-daemon`?

**Comment by ppp0** [comment]
By doing some changes to the init script, I'd say definitely yes. I will investigate in how many instances we do logging like this (`start-stop-daemon >> logfile`)  I know only `janus` for sure..

**Comment by njam** [comment]
Ah, so seems like a very simple change.
Let's add it to `daemon` then!

**Comment by ppp0** [comment]
All custom-defined init scripts we're using are on software that comes with her own logging (e.g. bipbip, cm_janus, pulsar_rest_api, ...) - which is by far the preferred method. Not so for janus... well, they introduce it in https://github.com/meetecho/janus-gateway/commit/f82a860522799f0312e905e1ba42c3971ea305e7

This would **obsolete** this issue for the moment

**Comment by ppp0** [comment]
I'm now going to close this, as all daemons in use implement their own logging (which is good practice anyway). Please reopen if you disagree
