### ISSUE TITLE
Discard apache2, phpmyadmin module

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1184]
Not used anymore

**Comment by ppp0** [comment]
Port phpmyadmin to nginx frontend instead of discarding?

@cargomedia/devops votes please

I vote -1

**Comment by tomaszdurka** [comment]
Well it's not good to keep modules we don't keep up to date. 
Still remember that all these modules are still with librarian puppet by passing a git reference, like:
```ruby
mod "maven",
  :git => "https://github.com/maestrodev/puppet-maven.git",
  :ref => 'v1.0.0'
```

I vote for removing if it's outdated?

**Comment by ppp0** [comment]
There is still passenger (puppet master) using apache2, so I better close this until https://github.com/cargomedia/puppet-packages/issues/1185 is realized
