### ISSUE TITLE
Puppet master passenger with nginx/fcgi? instead of apache2/mod_passenger

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1185]
To get rid of our apache depedency..

**Comment by njam** [comment]
I think the new puppetserver version 4 doesn't use apache anymore.
Can you confirm?
If so, I think we can close it in favor of https://github.com/cargomedia/puppet-packages/pull/1068

**Comment by ppp0** [comment]
Agree, looks like the new, rebranded "Puppet Server" is JRuby running in a JVM
