### ISSUE TITLE
Add janus roles

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1193]
continued from #1181

**Comment by ppp0** [comment]
Roles for
* audioroom
* rtpbrodcast
* origin/repeater/edge

whatnot

**Comment by kris-lab** [comment]
I think this will be done a bit differently by Tomasz. However most of this is done already in another threads.

please re-open if disagree.

**Comment by njam** [comment]
See https://github.com/cargomedia/puppet-packages/issues/1308
