### ISSUE TITLE
Daemon: start service on install

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages#1197]
Should be configurable `start_on_install = true`.

cc @njam @ppp0

**Comment by ppp0** [comment]
so `daemon` should know about `package`?

**Comment by kris-lab** [comment]
Actually it is implemented for sysvinit https://github.com/cargomedia/puppet-packages/blob/master/modules/sysvinit/manifests/script.pp#L16 and systemd https://github.com/cargomedia/puppet-packages/blob/master/modules/systemd/manifests/unit.pp#L18 

Anyway, service is not starting for some reason.

**Comment by kris-lab** [comment]
Closing this. All seems to work fine.
