### ISSUE TITLE
Add janus-gateway-cluster audioroom role

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages#1205]
Part of #1181 and https://github.com/cargomedia/puppet-cargomedia/issues/1080

**Comment by kris-lab** [comment]
I guess it is not needed. We install this role as `cm::services::janus` or maybe you prefer this with specific `janus::role::audioroom` which would re-implement `cm::services::janus`?

closable?

**Comment by njam** [comment]
agree, we can install "standalone" here.
