### ISSUE TITLE
janus rtpbroadcast: add bipbip metric for "inbound packet loss"

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#1207]
And maybe also for "keyframe-overdue" (to replace the logparser entry)?

Related to https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/69
cc @landswellsong @tomaszdurka

**Comment by njam** [comment]
Waiting on https://github.com/cargomedia/janus-gateway-rtpbroadcast/pull/69

Maybe should rather go to bipbip?

**Comment by kris-lab** [comment]
This must be implemented in bipbip. Follow up https://github.com/cargomedia/bipbip/issues/145
