### ISSUE TITLE
cm::services::janus: recording

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#1211]
Regarding recording, seems there is a bug.
- `cm::services::janus` *expects* `'yes'`/`'no'` value
- janus plugin expects boolean (most probably treats `'no'` as `true`

Should we always use boolean?
cc @tomaszdurka

**Comment by tomaszdurka** [comment]
You agree with always using boolean? If so, done in #1209

**Comment by kris-lab** [comment]
According to janus implementation https://github.com/meetecho/janus-gateway/blob/master/utils.c#L41 it should accept `true`, `yes`, `1` as enabled.

**Comment by tomaszdurka** [comment]
Oh, ok. But within the plugin define you manually check it against boolean and adjust `yes`/`no`.

I would keep it as boolean. How we put it into the config is other thing and yes/no is fine with me.

**Comment by kris-lab** [comment]
Agree, boolean should work.

**Comment by tomaszdurka** [comment]
This has been resolved with #1209.
