### ISSUE TITLE
Add logrotate for coturn

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#1217]
Log is quite big already

cc @kris-lab

**Comment by ppp0** [comment]
this is weird, there is a logrotate already? At least [in the code](https://github.com/cargomedia/puppet-packages/blob/master/modules/coturn/manifests/init.pp#L51)

**Comment by njam** [comment]
True. Looks like our turn server was connected to *a lot* in the last 24h, that's why the log got a bit big.

![screen shot 2016-03-21 at 17 18 43](https://cloud.githubusercontent.com/assets/360800/13925556/fceb9c20-ef88-11e5-8ada-419ffad1ea38.png)

```
/var/log/coturn$ ls -lh
total 282M
-rw-r--r-- 1 turnserver turnserver 275M Mar 21 16:19 turnserver.log
-rw-r--r-- 1 turnserver turnserver 272M Mar 21 06:25 turnserver.log.1
-rw-r--r-- 1 turnserver turnserver 1.3M Mar 20 06:25 turnserver.log.2.gz
-rw-r--r-- 1 turnserver turnserver 1.5M Mar 19 06:25 turnserver.log.3.gz
-rw-r--r-- 1 turnserver turnserver 865K Mar 18 06:25 turnserver.log.4.gz
-rw-r--r-- 1 turnserver turnserver 915K Mar 17 06:25 turnserver.log.5.gz
-rw-r--r-- 1 turnserver turnserver 915K Mar 16 06:25 turnserver.log.6.gz
-rw-r--r-- 1 turnserver turnserver 946K Mar 15 06:25 turnserver.log.7.gz
```

Is there a way to make it less verbose? Only log warnings?

**Comment by ppp0** [comment]
looks like there's a huge compression potential (lots of redundancies)!

**Comment by njam** [comment]
can you check if there is a way to log only warnings?

**Comment by ppp0** [comment]
Looks like we actually are in a less verbose mode than possible:
```
# Uncomment to run TURN server in 'normal' 'moderate' verbose mode.
# By default the verbose mode is off.
#verbose

# Uncomment to run TURN server in 'extra' verbose mode.
# This mode is very annoying and produces lots of output.
# Not recommended under any normal circumstances.
#
#Verbose

```

What we could try doing is offload this "noise", filtering it out with `rsyslog::config` (similar to https://github.com/cargomedia/puppet-packages/blob/master/modules/ufw/templates/rsyslog.erb) - explained in https://www.howtoforge.com/community/threads/system-logging-dont-log-something.5230/#post-188765

**Comment by njam** [comment]
oh, strange.

let's ignore it for now?

**Comment by ppp0** [comment]
There is an unimplemented function stub to use an external logger (https://github.com/coturn/coturn/blob/e544a6c0f2578251f56d1da22a1b27a3ef12d9c4/src/apps/common/ns_turn_utils.c#L151)

Unfortunately, they do have log levels, but one can't set the verbosity based on it. (https://github.com/coturn/coturn/blob/e544a6c0f2578251f56d1da22a1b27a3ef12d9c4/src/apps/common/ns_turn_utils.h#L52)
Shall I open a feature request?

**Comment by njam** [comment]
sgtm

**Comment by ppp0** [comment]
https://github.com/coturn/coturn/issues/39
