### ISSUE TITLE
Robustness of tests when relying on 3rd parties

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1239]
It happens quite often that specs fail when a 3rd party, such as an external repo (`apt.puppetlabs.com`) or an external server are not reacheable for some reason.

May be we should mock those? Or keep a local mirror / cache of the needed resources additionally to polipo?

**Comment by njam** [comment]
Mocking all of that will be very difficult for acceptance testing.
I would suggest to just retry those specs: https://github.com/cargomedia/puppet-packages/issues/885
wdyt?

**Comment by ppp0** [comment]
* I agree mocking has to be a quite actual mirror, not a mock
* The problem with #885 is that a network outage might last long enough to make all repetitions fail while it might be gone a couple of hours later.
* Something like a local, cache, transparent to the VM which updates itself twice a day would be nice

But surely #885 might be worth a try

**Comment by njam** [comment]
Since the goal of the acceptance tests is to make sure these modules work, even "in the wild", I think it's good to depend on external dependencies. If some external URL is not available anymore we might have to update our modules.
Let's do #885 and see how it goes?
