### ISSUE TITLE
janus+plugins: stick to fixed version

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages#1253]

**Comment by njam** [comment]
Maybe only in puppet-cargomedia?

**Comment by njam** [comment]
Hm, but it's not possible with apt is it?

**Comment by kris-lab** [comment]
Oh really? So this one is also not possible https://github.com/cargomedia/puppet-packages/issues/1250 ?

**Comment by njam** [comment]
#1250 is just about replacing `ensure => latest` with `ensure => present`, so puppet doesn't automatically upgrade if an older version is already installed (and we can upgrade manually with `apt-get`).

Since we don't host old DEBs on our repo there's no way we can install older versions.

**Comment by kris-lab** [comment]
So what do you recommend to make sure we do not install latest janus plugins for VM create?

**Comment by njam** [comment]
How about we *don't* release a deb yet, and install from git. And only release a deb once everything is working and can be released?
```json
{
  "janus::common::src_version": "adf88c5a7f7c103b28a65f6229cc6cd7ed64dcef",
  "janus::common_audioroom::src_version": "v0.0.8",
  "janus::common_rtpbroadcast::src_version": "v0.0.10"
}
```

**Comment by kris-lab** [comment]
ok for me

**Comment by njam** [comment]
Ok closing then
