### ISSUE TITLE
[Feature] Upgrade to mongodb 3.2

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#1255]
Part of https://github.com/cargomedia/puppet-cargomedia/issues/1747

Current version 2.6 is approaching end of life, and MMS will stop supporting it at the end of October, 2016.
https://www.mongodb.com/blog/post/mongodb-2-6-end-of-life

Also version 3 has some very interesting performance improvements.

**Comment by kris-lab** [comment]
Test plan:
- [ ] restore `rep1` locally
- [ ] upgrade manually
- [ ] verify with SK dev app

**Comment by kris-lab** [comment]
Upgrade recommendation https://docs.mongodb.com/v3.0/tutorial/install-mongodb-on-debian/

**Comment by kris-lab** [comment]
Upgrade from 3.0 to 3.2
- [ ] https://docs.mongodb.com/manual/release-notes/3.2-upgrade/

**Comment by njam** [comment]
Blocked by https://github.com/cargomedia/cm/pull/2331

**Comment by kris-lab** [comment]
Follow up https://github.com/cargomedia/puppet-packages/pull/1639
