### ISSUE TITLE
Upgrade jenkins to >v2.2 failed

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1320]
We had to downgrade to v2.2

Some issues with pushes not triggering a build

Output e.g.
```
GitHub pull request #1313 of commit 7cdd85323024908479e8a2a897c186314db866c5, no merge conflicts.
Building remotely on ci5.cargomedia.ch in workspace /var/lib/jenkins/workspace/cargomedia-puppet-packages-pr
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url ssh://git@github.com/cargomedia/puppet-packages.git # timeout=10
Fetching upstream changes from ssh://git@github.com/cargomedia/puppet-packages.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress ssh://git@github.com/cargomedia/puppet-packages.git +refs/pull/*:refs/remotes/origin/pr/*
 > git rev-parse origin/${sha1}^{commit} # timeout=10
 > git rev-parse ${sha1}^{commit} # timeout=10
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Finished: FAILURE
```

ghprb:
- Website: https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin
- Changelog: https://github.com/jenkinsci/ghprb-plugin#updates

**Comment by ppp0** [comment]
Yesterday same issue with v2.5

**Comment by njam** [comment]
@ppp0 did you change some APT configuration so that the upgrade doesn't happen automatically?  Please document it here if yes.

**Comment by ppp0** [comment]
Unfortunately, it is not possible without a deeper investigation.
 `apt-mark hold <package>` is to be set *just before* apt upgrading, but *to be released afterwards*. If not, you will have puppet errors at every run.

**Comment by njam** [comment]
Seems to be fixed in newer versions: https://wiki.jenkins-ci.org/display/JENKINS/Plugins+affected+by+fix+for+SECURITY-170
Will prepare an upgrade.

**Comment by njam** [comment]
Upgraded to 2.7.
Github triggered build works: http://ci.cargomedia.ch:8080/job/cargomedia-test-pr/2/console
