### ISSUE TITLE
"new" warning on puppet1

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1333]
This is the first entry, we get this now at every puppet run:
`May 23 10:18:24 puppet1 puppet-agent[24051]: Could not match Warning: The following options to parse-opts are unrecognized: :flag``

**Comment by ppp0** [comment]
This is causing the warning at every puppet run:
```sh
root@puppet1.cargomedia.ch:/home/admin$ /opt/puppetlabs/bin/puppetserver gem list --local
Warning: The following options to parse-opts are unrecognized: :flag

*** LOCAL GEMS ***

deep_merge (1.0.1)
ipaddress (0.8.3)
jar-dependencies (0.1.13)
jruby-openssl (0.9.7 java)
json (1.8.0 java)
rake (10.1.0)
rdoc (4.1.2)
```

**Comment by ppp0** [comment]
Closing for the moment (It's just a warning...)

**Comment by bahner** [comment]
Please repoen this. This warning makes the client have "Changed" status for every run. This does not dashboard well :-)

**Comment by ppp0** [comment]
@bahner thanks for reporting

**Comment by kris-lab** [comment]
@bahner @ppp0 I would suggest to move the tracking of this problem to the `puppetserver` repo? It is not related to our implementation imo. wdyt?

**Comment by ppp0** [comment]
To me it looks like (again) `rubygems` is to blame :( - But I agree, has not to do with our repo

**Comment by kris-lab** [comment]
I am gonna close it. Please reference external ticket once it is done.
