### ISSUE TITLE
META: make Janus & services - Jessie compatible

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages#1346]
Part of https://github.com/cargomedia/puppet-cargomedia/issues/645
Part of https://github.com/cargomedia/puppet-packages/issues/1242

- [x] janus
- [x] cm-janus
- [x] `coturn`  (#1384)
- [x] cm::services
- [x] `sk::janus`

cc @ppp0

**Comment by kris-lab** [comment]
@ppp0 as discussed please compile full list of modules needed for migration.

**Comment by ppp0** [comment]
- [ ] ca_certificates
- [ ] database
- [ ] ffmpeg
- [ ] janus
- [ ] lame
- [ ] mysqltuner
- [ ] nodejs
- [ ] systemd
- [ ] helper
- [ ] apt
- [ ] autoprefixer
- [ ] bash
- [ ] bipbip
- [ ] browserify
- [ ] build
- [ ] cgi_fcgi
- [ ] cm
- [ ] cm_janus
- [ ] composer
- [ ] coturn
- [ ] cron
- [ ] daemon
- [ ] elasticsearch
- [ ] environment
- [ ] fluentd
- [ ] foreman
- [ ] gearman
- [ ] git
- [ ] github
- [ ] iptables
- [ ] irqbalance
- [ ] janus
- [ ] kernel
- [ ] lame
- [ ] logrotate
- [ ] memcached
- [ ] mjr_convert
- [ ] mongodb
- [ ] monit
- [ ] mysql
- [ ] mysql_proxy
- [ ] mysqltuner
- [ ] network
- [ ] nginx
- [ ] ntp
- [ ] percona_toolkit
- [ ] phantomjs
- [ ] php5
- [ ] phpunit
- [ ] postfix
- [ ] puppet
- [ ] raid
- [ ] redis
- [ ] rsync
- [ ] rsyslog
- [ ] ruby
- [ ] socket_redis
- [ ] ssh
- [ ] sudo
- [ ] sysctl
- [ ] timezone
- [ ] ufw
- [ ] uglify
- [ ] ulimit
- [ ] vim
- [ ] wowza

**Comment by kris-lab** [comment]
Ok, so we have still 20-30 modules to go to make it compatible? Is it all related sk app?

**Comment by ppp0** [comment]
I went recursively (but manually :( ) through the Puppetfiles

**Comment by njam** [comment]
btw I posted a script to do this in https://github.com/cargomedia/puppet-packages/issues/1242:
https://gist.github.com/njam/cd15c444a74e531a6ce26ccbe5935a08

**Comment by njam** [comment]
tricky ones?: elasticsearch, mysql, coturn, memcached, mongodb, wowza

**Comment by ppp0** [comment]
No to forget: (sk app deployment)

**exec** `systemctl daemon-reload` between `foreman-debian install` and `foreman-debian start`

**Comment by njam** [comment]
Basically [foreman-debian](https://github.com/cargomedia/foreman-debian) needs systemd support. @ppp0 wanna open a ticket there?

**Comment by ppp0** [comment]
I completely agree! The problem I see is that the reason to add a suffix `-debian` to foreman was to denote the fact that it is kind of a clone of foreman. Which itself supports systemd! (see http://ddollar.github.io/foreman/#SYSTEMD-EXPORT)

May be I'm completely mistaken and then yes, we could start supporting systemd in foreman-debian. I'll wait with opening a ticket before this is clarified

**Comment by kris-lab** [comment]
As discussed with @ppp0 let's split the work in between us. See https://github.com/cargomedia/puppet-packages/issues/1346#issuecomment-227125460

**Comment by kris-lab** [comment]
Quick update of what left with modules (janus aimed) transition:
- [ ] elasticsearch #1415 
- [ ] memcached (#1424)
- [ ] mysql (#1243)
- [ ] mysql_proxy (#1425)
- [ ] phpunit (#1426)

also with general compatibility:
- [ ] disable mongodb logs https://github.com/cargomedia/puppet-packages/issues/1430
- [ ] disable logs for janus https://github.com/cargomedia/puppet-packages/issues/1377
- [ ] foreman-debian https://github.com/cargomedia/pulsar-conf-cargomedia/issues/331

**Comment by kris-lab** [comment]
Gonna close it in favor of https://github.com/cargomedia/puppet-packages/issues/1242#issuecomment-240039622

**Comment by kris-lab** [comment]
Please re-open if disagree. Site note: currently Jessie with SK application is running on janus4.
