### ISSUE TITLE
[jenkins] - Config changes not reflected into xml files

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1360]
We merged https://github.com/cargomedia/puppet-cargomedia/pull/1239 this yesterday but 
/var/lib/jenkins/org.jenkinsci.plugins.ghprb.GhprbTrigger.xml
/var/lib/jenkins/org.jenkinsci.plugins.ghprb.GhprbTrigger-puppet.xml

were not modified..

**Comment by njam** [comment]
That `exec { $config_jenkins` in `jenkins::plugin::ghprb` should notify the service.

**Comment by ppp0** [comment]
Actually, the `/var/lib/jenkins/org.jenkinsci.plugins.ghprb.GhprbTrigger-puppet.xml`was *not modified* so "that exec" had little to do

**Comment by kris-lab** [comment]
As investigated with @ppp0 the PR was not applied properly https://github.com/cargomedia/puppet-cargomedia/pull/1239 

Follow up https://github.com/cargomedia/puppet-cargomedia/issues/1249
