### ISSUE TITLE
Disable log file of janus

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#1377]
After https://github.com/cargomedia/puppet-packages/issues/1346

With systemd janus logs directly to journald.
So we should disable logging to a separate file, and remove the fluentd source (because we have it from syslog).

cc @ppp0

**Comment by kris-lab** [comment]
Temporary closing this ticket for better visibility. Will be done according to finding in https://github.com/cargomedia/puppet-cargomedia/issues/1411#issuecomment-258804467
