### ISSUE TITLE
Modules for webrtc testing

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1386]
Some modules are not yet there:
- [ ] `chromium`: on Jessie, package name differs from Vivid (#1388)
- [ ] Chrom[e|ium] Driver (https://sites.google.com/a/chromium.org/chromedriver/)
- [ ] x11vnc
- [ ] fluxbox (Really needed? @zazabe )
- [ ] Check alleged dependencies

**Comment by ppp0** [comment]
Needed for https://github.com/cargomedia/sk/pull/2867

**Comment by kris-lab** [comment]
as discussed with @ppp0 let's close it
