### ISSUE TITLE
Update of Screenconnect Clients

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1393]
Right now, the install procedure does not take account of the client's version. In the web GUI we're starting to see warnings for the older nodes
![screen shot 2016-07-18 at 17 10 39](https://cloud.githubusercontent.com/assets/1888714/16919728/22153724-4d0b-11e6-8bbc-47b0cdfb168d.jpg)

There is a page where Donwloads are listed, but not as a `deb` installer
https://www.screenconnect.com/Download

**Comment by ppp0** [comment]
I was able to trigger a remote update of the client by selecting the nodes and issuing the command "reinstall"

<img width="211" alt="screen shot 2016-07-19 at 12 27 56" src="https://cloud.githubusercontent.com/assets/1888714/16946961/8c1462c0-4dac-11e6-8e33-707a814bd30d.png">

not sure, though, if this is automation enough. Otoh, it has not to be done often

**Comment by kris-lab** [comment]
I think for now this manual re-installation is fine. wdyt?

**Comment by ppp0** [comment]
Closing. I had to intervene on a node (bd5) because the update script was hanging. I then `apt-get autoremove`d screenconnect and let puppet redo the installation (to the newest version)
