### ISSUE TITLE
Better version management for Chromium bleeding-edge

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1395]
Continuation of #1388

**Comment by ppp0** [comment]
It is quite difficult to manage now because there is a version like
````
$ chromium-browser --version
Chromium 51.0.2704.0 
```

but this is referenced as revision Linux_64/386257

May be there is a proven way to identify version numbers

**Comment by ppp0** [comment]
Interesting, http://googlechromereleases.blogspot.ch/2016/06/stable-channel-update_16.html

That means, 51.0.2704.103 and upwards can't really be named "bleeding-edge" anymore.. ?

**Comment by ppp0** [comment]
Another tool to translate version to arch/rev number: https://omahaproxy.appspot.com/

**Comment by kris-lab** [comment]
Also this is interesting http://superuser.com/a/374157 and http://omahaproxy.appspot.com/viewer

**Comment by njam** [comment]
This is for Ubuntu? Maybe just use these PPAs which seem popular:
https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-beta
https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-dev

**Comment by njam** [comment]
Closing in favor of https://github.com/cargomedia/janus-gateway-js/issues/98
