### ISSUE TITLE
Upgrade fluentd to 0.14

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#1427]
Releases: https://github.com/fluent/fluentd/releases

0.14 enables sub-second time resolution (see https://github.com/cargomedia/puppet-cargomedia/pull/1340).

We downgraded to 0.12 in: https://github.com/cargomedia/puppet-packages/pull/1349
Since then there's a new 0.14.1

**Comment by ppp0** [comment]
We had issues with Wheezy's outdated ruby and with rubygems, too (was resolving dependencies wrongly)

**Comment by njam** [comment]
Unfortunately 0.14.6 didn't send events to Loggly anymore.
Reverting to 0.12 for now.
Will investigate and test tomorrow.

**Comment by njam** [comment]
Tickets:
- **fluent-plugin-forest**: Buffered output doesn't work since 0.14 https://github.com/tagomoris/fluent-plugin-forest/issues/32
- **fluent-plugin-loggly**: Upgrade to fluentd 0.14 API https://github.com/patant/fluent-plugin-loggly/issues/19

**Comment by njam** [comment]
0.14.8. deployed
