### ISSUE TITLE
Disable log for mongodb

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1430]
Similar to https://github.com/cargomedia/puppet-packages/issues/1377

In systemd all daemons should just dump their output to stdout stderr
journald will take care of storing/rotating

No more log files all over the place, log rotation etc.

Solves https://github.com/cargomedia/puppet-packages/pull/1421

**Comment by ppp0** [comment]
Keep wheezy compatibilty until phased out

**Comment by kris-lab** [comment]
sgtm

**Comment by kris-lab** [comment]
Temporary closing this ticket for better visibility. Will be done according to finding in https://github.com/cargomedia/puppet-cargomedia/issues/1411#issuecomment-258804467
