### ISSUE TITLE
Jessie: install FFmpeg without custom "backports" source

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages#1444]
Part of https://github.com/cargomedia/sk/pull/3620

The idea is to install `ffmpeg` with backports source or by cloning backports DEB into cargomedia. 

Currently we meet the problem with globally enabled `backports` source which affects all installed packages.

**Comment by njam** [comment]
I would suggest to rather change the priority of the sources, so that by **default packages are installed from the normal sources**, and **specific packages can be installed from backports**.

See http://unix.stackexchange.com/questions/71181/upgrade-a-single-package-from-a-target-release

**Comment by kris-lab** [comment]
Thanks, will try to accomplish this way.

**Comment by kris-lab** [comment]
This is false problem. I do not experience this anymore.

The explanation for this issue was my `/etc/resolve.conf` (with my local router) which for some reason confused DNS when `security.debian.org` was requested. As the fallback `apt-get` was using `backports` which was available atm.

Pointing `resolve.conf` to `8.8.8.8` solved the problem.

closing, please re-open if needd.

**Comment by njam** [comment]
What? :)
So backports has lower prio by default, and mysql 5.5 is installed by default?

**Comment by njam** [comment]
Yes, I can confirm it:
```
ii  mysql-server                         5.5.49-0+deb8u1                   all          MySQL database server (metapackage depending on the latest version)
```

**Comment by kris-lab** [comment]
yes, indeed! :)
