### ISSUE TITLE
Debian-8: migrate TrueCrypt module

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages#1448]
This problem might be tricky to solve. The main issue is missing `libwxbase2.8` which is available currently in version `libwxbase3.0` on `Jessie`. It doesn't compile all together. Also it's recommended to not use in general (some replacement https://tails.boum.org/blueprint/replace_truecrypt/)

We need this module for at least `s3export_backup`!

needs to be investigated deeper...

cc @ppp0 @njam

**Comment by kris-lab** [comment]
Options:
- try to compile without libwxbase
- use AWS products
- use in Wheezy box at mandrill
- migrate libwxbase2.8 into Jessie
- use hardware encrypted HDD (pincode)

**Comment by kris-lab** [comment]
What about https://www.istorage-uk.com/product/diskashur-dt/

<img width="1177" alt="screen shot 2016-08-22 at 11 22 48" src="https://cloud.githubusercontent.com/assets/1843523/17851631/d12d7a22-685a-11e6-9c58-f48ff7ca0b1b.png">

cc @njam @ppp0

**Comment by njam** [comment]
lgtm

**Comment by kris-lab** [comment]
Alternatively it can be purchased from https://www.amazon.co.uk/iStorage-diskAshur-USB3-256-bit-Inch/dp/B00EPBTXHG/ref=sr_1_1?s=computers&ie=UTF8&qid=1471953120&sr=1-1&keywords=iStorage+diskAshur+4TB

**Comment by kris-lab** [comment]
I consider this ticket (topic) as undoable at the moment. We will use hardware solution and most likely VM for data verification.

@njam @ppp0 agree to close?

**Comment by njam** [comment]
agree
