### ISSUE TITLE
Debian-8: cgroups module upgrade

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages#1458]

**Comment by kris-lab** [comment]
@njam @ppp0 this module is possible to upgrade, however:
- we use currently `sysvinit` to install ["fake"](https://github.com/cargomedia/puppet-packages/blob/master/modules/cgroups/templates/init) service to make sure all configuration is applied at the boot time
- after migrate, we would use this logic (`/etc/init.d/cgconfig-apply` for both: sysvinit and systemd
- we agreed to [remove `sysvinit`](https://github.com/cargomedia/puppet-cargomedia/issues/1363) module after upgrade to Jessie, so I would not use `sysvinit` module, but rather create the file with content manually?

wdyt?

**Comment by ppp0** [comment]
I don't know, I thought all this cgroups and resource reservation stuff is now managed by `systemd` ?
See http://0pointer.de/blog/projects/resources.html and http://man7.org/linux/man-pages/man5/systemd.cgroup.5.html

**Comment by kris-lab** [comment]
Yes, this it true. `cgroup` gives you ability to control also processes which are not managed by `systemd`. The `cgconfig-apply` service is only for applying configuration at the boot time.

**Comment by njam** [comment]
We can drop, and re-add it if needed.

**Comment by kris-lab** [comment]
👍

**Comment by kris-lab** [comment]
Closing for now
