### ISSUE TITLE
Janus/rtpbroadcast package should be "ensure=>held"

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages#1495]
Pining to specific version has been introduced #1494 

We should make sure that puppet will `held` this package.
```
(/Stage[main]/Janus::Common_rtpbroadcast/Package[janus-gateway-rtpbroadcast]/ensure) ensure changed 'held' to 'present'
```

**Comment by njam** [comment]
Isn't "present" okay?

**Comment by kris-lab** [comment]
Every puppet run outputs `ensure changed 'held' to 'present'`

**Comment by njam** [comment]
It's not the case on www7, where "imagemagick-common" is pinned.
So maybe it's a remnant from the previous approach `apt-mark hold`?

**Comment by kris-lab** [comment]
Yep, I think you are right! Will verify

**Comment by kris-lab** [comment]
Confirmed, APT pinning and holding do not work well with puppet ensure!
