### ISSUE TITLE
Make revive compatible with Jessie

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages#1512]
Part of https://github.com/cargomedia/puppet-cargomedia/pull/1532

> [10:35 AM] Chris Stasiak: Ads server, more specifically the openx/revive requires mysql-server@5.6. So far it was provided by dotdeb repo. Currently we removed dotdeb, because of conflicts with Jessie. However we need to install mysql@5.6 to make openx/revive happy or we should somehow hack the database.

**Comment by njam** [comment]
Here they say it needs 4.1 :D Where do you see 5.6?
https://www.revive-adserver.com/support/requirements/

**Comment by kris-lab** [comment]
I haven't read documentation yet. Current `ads2` is mysql@5.6 so migration of database into 5.5 is not possible atm.

Also I am pretty sure the requirements has been change for last versions of revive :)

The question is not about installing fresh revive, but about our specific case to migrate 5.6 into 5.5 or upgrading ads2 with mysql@5.6.

**Comment by ppp0** [comment]
mysqldump ?

**Comment by kris-lab** [comment]
For records, this is the initial error
```
ERROR 1064 (42000) at line 320: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'STATS_PERSISTENT=0' at line 11
```

**Comment by kris-lab** [comment]
For records, my migrations steps:
Old one:
```
mysqldump -u root --all-databases > dump.sql
```
New one:
```
mysql -u root  < /home/admin/dump.sql 
```

**Comment by ppp0** [comment]
http://stackoverflow.com/questions/33811441/restoring-schema-backup-from-mysql-5-6-to-5-5

**Comment by kris-lab** [comment]
Related issues:
- https://bugs.mysql.com/bug.php?id=70778
- https://www.quora.com/What-does-error-1064-mean-when-restoring-a-MySQL-dump
- patch for 5.6 bug and STATS_PERSISTENT  -> https://bugs.mysql.com/file.php?id=22279&bug_id=70778

**Comment by kris-lab** [comment]
@ppp0 @njam wdyt think to downgrade schema according to official documentation https://dev.mysql.com/doc/refman/5.6/en/downgrading-to-previous-series.html and stick to mysql@5.5 on the revive server?

**Comment by ppp0** [comment]
Fully agree to stick with 5.5 if this is possible

**Comment by njam** [comment]
Agree!

**Comment by njam** [comment]
About `STATS_PERSISTENT=0`: http://serverfault.com/questions/679805/removing-stats-persistent-0-for-innodb

**Comment by kris-lab** [comment]
Confirmed. Manual removal of `STATS_PERSISTENT` allows to restore revive database.

**Comment by kris-lab** [comment]
Closing, it works.
