### ISSUE TITLE
Rework mysql::service

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1526]
This bug report is allegedly fixed: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=741286

So may be we can get rid of our *hacky* service start/stop config? We're relying on `daemon` anyway, and a timeout when stopping is defined

**Comment by njam** [comment]
The issue wasn't fixed, but:
> as the package mysql-5.5 has just been removed from the Debian archive
unstable we hereby close the associated bug reports.  We are sorry
that we couldn't deal with your issue properly.

But agree, this should be definitely removed, as it will be properly handled by systemd.

**Comment by ppp0** [comment]
Oh, I was reading
>Fixed in version 5.5.46-0+deb8u1+rm

and made some (too quick?) conclusions

**Comment by ppp0** [comment]
Solved in https://github.com/cargomedia/puppet-packages/issues/1536
