### ISSUE TITLE
Remove version pinning from Imagick extension

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1527]

**Comment by ppp0** [comment]
Waiting for https://github.com/cargomedia/puppet-packages/pull/1524

**Comment by njam** [comment]
@ppp0 what's the status?

**Comment by ppp0** [comment]
@njam status is: in progress

**Comment by ppp0** [comment]
Looks like the issue's been (accidentally?) solved in commit https://github.com/cargomedia/puppet-packages/pull/1524/commits/a6ede479a5855bce78e8563c4d06294550f4a294 of #1524

**Comment by ppp0** [comment]
Resources (apt::preferences need to be purged where applicable and imagick and its libraries reinstalled) @kris-lab cc

**Comment by ppp0** [comment]
Resources purges. At next CRON-APT run we'll be asked to upgrade imagick-related packages

**Comment by ppp0** [comment]
See https://github.com/cargomedia/puppet-cargomedia/issues/1558 for further comments
