### ISSUE TITLE
Remove sysvinit stuff

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#1532]
There are some usages of init scripts around that can/should be removed/changed.

@ppp0 @kris-lab can you check it?

**Comment by ppp0** [comment]
The only place I see which could need a refurbishment in `mysql::service`
The rest is either to be deleted by #1498 or by refactoring our log rotation
Where do you see other usages that need intervention?

**Comment by njam** [comment]
- backup/templates/agent/rdiff/create.sh
- mysql/manifests/service.pp
- mysql/templates/replication-check.sh
- puppetserver/manifests/puppetdb/certs.pp

wdyt?

**Comment by ppp0** [comment]
closing as completed. Reopen if you disagree
