### ISSUE TITLE
[proxy-cache] - apt install fails with inability to authenticate

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#1567]
Now that caching happens on deb level, `apt get install` fails with e.g.
```
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install ssh' returned 100: Reading package lists...
      Building dependency tree...
      Reading state information...
      The following NEW packages will be installed:
        ssh
      0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
      Need to get 7168 B of archives.
      After this operation, 112 kB of additional disk space will be used.
      WARNING: The following packages cannot be authenticated!
        ssh
      E: There are problems and -y was used without --force-yes
```

The error being `WARNING: The following packages cannot be authenticated!` 

This can be reproduced locally, too, by executing a spec twice (without "keep_ box=true")

A first search on Google results in people experiencing those problems when using proxies. The advisory is to `apt-get update` which I confirmed to be working.

I don't know, though, if we shall apt update every time we run a spec. I'd prefer to skip authentication with `--force-yes`

@cargomedia/devops thoughts?

**Comment by njam** [comment]
I would not do `--force-yes`. It could be dangerous just for this use case, and will probably enforce various other prompts that we're not thinking of now (like uninstalling other packages or overwriting config etc).

I don't understand the problem completely. Let's say we have two test runs:
1. First run caches the **index** and caches the **ssh deb**. Both are downloaded from the same "snapshot" of the repo and thus succeed.
2. Second run uses the cached version of both the index *and* the ssh deb, and should therefore end with the same result?

What am I missing?

**Comment by kris-lab** [comment]
@ppp0 I suggest we pair on it? I also don't understand the source of all these caching problems.

**Comment by ppp0** [comment]
obsoleted by #1573
