### ISSUE TITLE
Add modules for Jetbrains tools

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#1646]
- Backup for data directory
- Run as daemon

Blueprints for Docker:
- Hub: https://github.com/dzwicker/docker-hub
- YouTrack: https://github.com/dzwicker/docker-youtrack
- UpSource: https://github.com/dzwicker/docker-upsource

**Comment by kris-lab** [comment]
Modules are done. More details https://github.com/cargomedia/puppet-cargomedia/issues/1784
