### ISSUE TITLE
Gearman restart exits with !=0

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#681]
It all started with #679 
Related: https://github.com/cargomedia/puppet-packages/issues/646

`service` will be notified, so it tries to `/etc/init.d/gearman restart`... Stopping is fine, but `monit` will notice process is not there anymore, so it will immediately start it. But this causes the restart script to complain:
```
==> default: Error: /Stage[main]/Gearman::Server/Service[gearman-job-server]: Failed to call refresh: Could not restart Service[gearman-job-server]: Execution of '/etc/init.d/gearman-job-server restart' returned 1: Stopping Gearman Server: gearmand.
==> default: Starting Gearman Server: gearmand/usr/sbin/gearmand already running.
==> default:  failed!
```

and `monit` 

```
Does not exist Service gearman-job-server

        Date:        Thu, 07 Aug 2014 06:29:48
        Action:      restart
        Host:        <beeeeeep>
        Description: process is not running
```

**Comment by ppp0** [comment]
I am not able to reproduce anymore :(  on VM...

On wowza2 I did a test restart:
```
root@wowza2.fuckbook.com:/home/admin$ /etc/init.d/gearman-job-server restart
[ ok ] Stopping Gearman Server: gearmand.
[....] Starting Gearman Server: gearmand/usr/sbin/gearmand already running.
 failed!
[warn] Please take a look at the syslog ... (warning).
```

Here the syslog:
```
2015-03-09T15:37:37.195951+00:00 wowza2 monit[16513]: 'gearman-job-server' process is not running
2015-03-09T15:37:37.260453+00:00 wowza2 monit[16513]: 'gearman-job-server' trying to restart
2015-03-09T15:37:37.260468+00:00 wowza2 monit[16513]: 'gearman-job-server' start: /etc/init.d/gearman-job-server
2015-03-09T15:37:47.338402+00:00 wowza2 monit[16513]: 'gearman-job-server' process is running with pid 32580
```

So it really looks like `monit` restarts `gearman` as soon as it sees that it is not running and this creates a race condition

**Comment by njam** [comment]
So monit doesn't stop gearman because there's no PID file maybe?

**Comment by ppp0** [comment]
Found the solution.. 
If we give a `--retry 5` (or less?) param to `start-stop-daemon` in https://github.com/cargomedia/debian-packages/blob/master/packages/gearmand/debian/gearman-job-server.init#L63 does not happen.

My theory is that the init script tries to start before gearman is fully stopped... Which is why a `sleep` between stop and start helps. `--retry` lets `start-stop-daemon` wait n seconds for the daemon to stop

**Comment by ppp0** [comment]
Solved by https://github.com/cargomedia/debian-packages/pull/5

**Comment by ppp0** [comment]
Close when checked that this is true

**Comment by ppp0** [comment]
Tested and confirmed to be solved
