### ISSUE TITLE
Wowza developer license

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages#783]
Can we have a perpetual license?

Part of https://github.com/cargomedia/puppet-packages/pull/667

**Comment by ppp0** [comment]
No answer nothing. They simply ignore us :( - [http://www.wowza.com/](Wowza Media Systems) Sales Reps or whoever - for the records, Google please index this

Give up?

**Comment by kris-lab** [comment]
The only question is: do we break any legal regulation (license) of them if we distribute private/developer license with open source code!?

Not sure to be honest. As far as I know if we do $0 (this is our case) then we are pretty much safe anyway!

**Comment by njam** [comment]
Agree, let's use developer licenses.

**Comment by ppp0** [comment]
In doubt, I would not distribute the license.. Could we store the key locally? If someone else wants to run the tests, he/she should first get a dev (or other) license from wowza?
