### ISSUE TITLE
Synchronous monit - Investigation

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#788]
According to https://bitbucket.org/tildeslash/monit/pull-request/9/add-new-keyword-sync-to-force-command-to/activity monit 5.9+ implements a keyword `sync` to make `monit` wait for the result of its actions (cf http://www.cargomedia.ch/2014/04/25/reliably-reloading-monit.html)

Investigate how exactly it works (docu/changelog does not mention it ?)

Upgrade version if suitable

**Comment by njam** [comment]
Newest monit has blocking `monit stop` and `monit start` by default.
All other actions are still async.

Reloading monit we have the `monit-alert` workaround - https://github.com/cargomedia/puppet-packages/pull/870

**Comment by njam** [comment]
> 5.9 waits for the stop/start commands to finish by default (both commands are synchronous now)

**Comment by ppp0** [comment]
:+1:  very good news
