### ISSUE TITLE
Double-check nginx' gzip_types

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#824]
We currently have:
```
gzip_types application/x-javascript text/css text/plain application/xml image/svg+xml;
```
in `vhost.pp`.

I just noticed that the landing page mp4-video on paypal.com is around 50% smaller thanks to gzipped transfer.
@kris-lab @ppp0 let's double check which file types should be zipped.

cc @nicolasschmutz

**Comment by kris-lab** [comment]
As we discussed:
- `paypal` is using partial content streaming (`Accept-Ranges: bytes`) but is not using any compression on streamed data. "Partial content" is supported by `nginx` from `1.7.7`.
- there is no easy way to compress video files on the fly using `gzip`
- video starts playing immediately if part of data is streamed to client

closing. if disagree please open.
