### ISSUE TITLE
tests failing for ruby::gem::bipbip

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#837]

**Comment by ppp0** [comment]
Failure was:
```
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install libmysqlclient-dev' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libmysqlclient18 mysql-common
The following NEW packages will be installed:
  libmysqlclient-dev libmysqlclient18 mysql-common
0 upgraded, 3 newly installed, 0 to remove and 29 not upgraded.
Need to get 1694 kB of archives.
After this operation, 9337 kB of additional disk space will be used.
Err http://security.debian.org/ wheezy/updates/main mysql-common all 5.5.40-0+wheezy1
  404  Not Found [IP: 127.0.0.1 8123]
Err http://security.debian.org/ wheezy/updates/main libmysqlclient18 amd64 5.5.40-0+wheezy1
  404  Not Found [IP: 127.0.0.1 8123]
Err http://security.debian.org/ wheezy/updates/main libmysqlclient-dev amd64 5.5.40-0+wheezy1
  404  Not Found [IP: 127.0.0.1 8123]
Failed to fetch http://security.debian.org/pool/updates/main/m/mysql-5.5/mysql-common_5.5.40-0+wheezy1_all.deb  404  Not Found [IP: 127.0.0.1 8123]
Failed to fetch http://security.debian.org/pool/updates/main/m/mysql-5.5/libmysqlclient18_5.5.40-0+wheezy1_amd64.deb  404  Not Found [IP: 127.0.0.1 8123]
Failed to fetch http://security.debian.org/pool/updates/main/m/mysql-5.5/libmysqlclient-dev_5.5.40-0+wheezy1_amd64.deb  404  Not Found [IP: 127.0.0.1 8123]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
[...]
```

`apt-get update` was needed.

This is no bug, as nothing can be done about it (except for requiring `apt-get update` to run on every `Package` resource inclusion?

I had to 
`vagrant destroy -f` to get rid of all snapshots and then `apt-get update` was invoked again as a dependency of https://github.com/cargomedia/puppet-packages/blob/master/spec/provision.pp#L4

**Comment by njam** [comment]
This is a known limitation. IIRC we decided we can live with this limitation that we need to `destroy` our box from time to time.
It might also become a problem on CI sooner or later (now that we don't destroy boxes anymore).
Maybe an optional one-time `apt-get update` in the CI script would be good? Or a rake-task, so it can also be run by devs?

**Comment by ppp0** [comment]
I tried to notify/refresh that resource `Class['apt::update']` (https://github.com/cargomedia/puppet-packages/blob/master/modules/apt/manifests/update.pp#L9) but in the end I was unsure where (see also https://github.com/cargomedia/puppet-packages/blob/master/spec/provision.pp)

The `refresh_only` makes sense IMO... or may be an `unless` which checks `/var/cache/apt/` for the age of the package metadata?

**Comment by njam** [comment]
hmmm, I like the `unless`, you wanna try?
