### ISSUE TITLE
Specs: Check that second puppet run applies 0 changes

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#850]
@cargomedia/devops wdyt?

Depends on https://github.com/cargomedia/puppet-packages/pull/829

**Comment by tomaszdurka** [comment]
I think we actually have cases where puppet run still *applies* something each run.
Still good to try and get rid of them.

**Comment by ppp0** [comment]
I was recently thinking if we shouldn't test the result of `unless` clauses after application? Not sure if this covers all scenarios where something would be applied again and again

**Comment by njam** [comment]
Closing for now, we have an alert on Copperegg
