### ISSUE TITLE
Upgrade Revive to 3.1.0

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#854]
@cargomedia/devops 

Manual upgrade on running instance?

**Comment by kris-lab** [comment]
I think this is the best option. From my experience there were always some problems!

(self-assign) if someone disagree please let me know.

**Comment by kris-lab** [comment]
Done. 

Related:
- puppet-packages -> https://github.com/cargomedia/puppet-packages/pull/867
- CM, blank impressions -> https://github.com/cargomedia/CM/pull/1679
