### ISSUE TITLE
Allow disabling proxy for specific specs

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/puppet-packages#871]

**Comment by njam** [comment]
Why does it affect only certain specs?

**Comment by njam** [comment]
http://linux.die.net/man/5/apt.conf - "the Acquire Group"

**Comment by tomaszdurka** [comment]
Actually it's not needed and done by disable proxy for Package via options (as done in https://github.com/cargomedia/puppet-packages/pull/869).
