### ISSUE TITLE
Update wowza config with transcoding/on-air-show base

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/puppet-packages#898]
General architecture requirements:
- [ ] publisher/subscriber instance configuration (av or audio only)
- [ ] edge instance configuration
- [ ] balancer instance configuration
- [ ] transcoder instance configuration

CM specific requirements:
- [ ] RPC address
- [ ] RTMP address for publisher
- [ ] RTMP adress for subscriber (load balancer)

**Comment by kris-lab** [comment]
@njam @tomaszdurka currently the `wowza::app::cm` has flat, single node configuration. I will extend that with at least `edge` and `balancer` role. If you have some thoughts, please share here. thx

**Comment by njam** [comment]
And if both roles are installed on the same machine, will it then run two wowza processes or one?

**Comment by kris-lab** [comment]
Basic `live` role and `edge` role can be installed in the same time. Basically at the end there are 2 separate applications in `wowza` server.

Regarding balancer... I am not sure yet. I hope it is possible so then we have full installation (ready fo scale) on single node!

**Comment by kris-lab** [comment]
AFAICS for built in wowza `balancer` it is bit tricky. This is because the default wowza balancer is able to work in or `server` or `member` mode.

```xml
<Properties>
    <Property>
        <Name>loadbalanceServerPort</Name>
        <Value>1935</Value>
    </Property>
    <Property>
        <Name>loadbalanceDebugEnabled</Name>
        <Value>Off</Value>
    </Property>
    <Property>
        <Name>loadbalanceAllowRemoteClientShutdown</Name>
        <Value>On</Value>
    </Property>
    <Property>
        <Name>loadbalanceType</Name>
        <Value>Server</Value>
    </Property>
    <Property>
        <Name>loadbalanceKey</Name>
        <Value>123456789012345</Value>
    </Property>
    <Property>
        <Name>loadbalanceIgnoreClients</Name>
        <Value>FMLE</Value>
    </Property>
    <Property>
        <Name>loadbalanceGeoDataFile</Name>
        <Value>[Install-dir]\GeoIP.dat</Value>
    </Property>
    <Property>
        <Name>loadbalanceDecisionOrder</Name>
        <Value>Geographic,Bandwidth,Connection</Value>
    </Property>
    <Property>
        <Name>loadbalanceServerIP</Name>
        <Value>SERVER IP</Value>
    </Property>
</Properties>
```

There are 2 options:
- try to run 2 separate wowza instances on single node? (I guess it is risky)
- find better 3rd party load balancer which would load balance to single or multiple end-points?

**Comment by njam** [comment]
and the "server" is not able to process requests?

**Comment by kris-lab** [comment]
Draft of puppet config update 
![pupet config - new page](https://cloud.githubusercontent.com/assets/1843523/7627435/896005b4-fa17-11e4-9bb8-0cb66d784111.png)

**Comment by kris-lab** [comment]
[Draft 2 of puppet config update](https://cloud.githubusercontent.com/assets/1843523/8160981/edcfbd9e-1373-11e5-8b0e-e88857ada51b.png) based on current [architecture stack concept](https://cloud.githubusercontent.com/assets/1843523/8159907/77320762-136b-11e5-9553-0ea698fa3690.png)

**Comment by kris-lab** [comment]
@njam what about closing this for now?

**Comment by njam** [comment]
agree
