### ISSUE TITLE
Jenkins Github OAuth not working

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#906]
Due to Github change. Probably need to upgrade the plugin version.

**Comment by ppp0** [comment]
These is likely the reason: https://developer.github.com/changes/2015-06-10-breaking-changes-to-organization-permissions-coming-on-june-24/#migration-period

What people [suggest here](https://gist.github.com/cosmo0920/c497e31692b03f1b8df6) is also somehow tampering with the authentication?

**Comment by njam** [comment]
I understand they suggest disabling security *temporarily* to gain access for being able to update the plugin (through the web UI).

**Comment by ppp0** [comment]
OK - well, give it a try!

**Comment by njam** [comment]
Works with 0.20

**Comment by ppp0** [comment]
excellent!
