### ISSUE TITLE
Remove net-ssh gem dependency workaround

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#938]
Introduced in #937 because of a dependency chain mismatch (ssh-kit was requiring a version of net-ssh which require ruby >=2.0)

As soon as https://github.com/capistrano/sshkit/blob/master/sshkit.gemspec#L20 is fixed, we can remove the stanza https://github.com/ppp0/puppet-packages/blob/issue-937/modules/capistrano/manifests/init.pp#L3

**Comment by njam** [comment]
> We won't be able to drop the workaround, see capistrano/sshkit#285 (comment)
  Delete branch


@ppp0 closeable?
