### ISSUE TITLE
Include Ubuntu modules here?

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#960]
@tomaszdurka @ppp0 @kris-lab as discussed

If we have separate repos we have various problems:
- Should keep modules and their signature in sync (otherwise hiera gets messy)
- Sandbox setup gets complicated with differences between production and sandbox (because we don't use librarian-puppet to install modules in sandbox).

It might be worth reconsidering keeping modules together in one repo.

All modules initially would only support debian. If the `lsbdistid` is not "Debian" and the `lsbdistrelease` is not "7" we would `fail("Unsupported OS")`.

For the specs we could add a file `os-support.json` to each module directory defining the expected success/failure:
```json
{
  "debian-7": true,
  "ubuntu-15.04": false
}
```

Let's decide tomorrow!

**Comment by ppp0** [comment]
I definitely see the problems that arise from having two repos, namespace being the biggest headache...
so probably sticking with one repo is the correct way to handle that. Remember when we migrated to wheezy. We had to lift the whole infrastructure to the new level which will not be possible nor desired today

**Comment by njam** [comment]
Plan:
- Add a `metadata.json` for each module with `operatingsystem_support` but empty `dependencies` (we're still using the `Puppetfile`)
 - [docu](https://docs.puppetlabs.com/puppet/latest/reference/modules_publishing.html#fields-in-metadatajson)
 - [example](https://github.com/puppetlabs/puppetlabs-ntp/blob/3.0.3/metadata.json)
- Run specs on all supported operatingsystem/VM

**Comment by ppp0** [comment]
closeable? Please reopen if you disagree
