### ISSUE TITLE
Upgrade Revive: 3.1.0 to 3.2.5

### ISSUE THREAD

**Issue by njam** [cargomedia/puppet-packages#971]
@ppp0 @kris-lab we should do it soon-ish I guess

**Comment by kris-lab** [comment]
Manual test has be done and failed. Upgrade seems to proceed and finish successfully but the version detected after upgrade is still at 3.1.0.

**Comment by njam** [comment]
Upgrading is more difficult than expected.
Let's put it on hold until we decide about the future of Revive https://github.com/cargomedia/sk-bizdev/issues/794

**Comment by njam** [comment]
We decided to re-install and re-configure Revive completely.
@kris-lab could you set up a new instance with the newest version, probably on a new domain? Once we have it we give access to Patrick so he can set it up.

**Comment by kris-lab** [comment]
Closing in favor of https://github.com/cargomedia/puppet-cargomedia/issues/1625
