### ISSUE TITLE
Set http-proxy environment variables while provisioning

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/puppet-packages#995]
Instead of using `vagrant proxyconf` on every single `vagrant ...` usage we could only trigger that in provision.

Either:
- find way to execute `proxyconf` only on provision (after initial polipo provision)
- set those variables on our own within provision script/manifest.

**Comment by tomaszdurka** [comment]
Example class
```
class { 'http_proxy':
    httpAddress  =>'http://localhost',
    httpsAddress =>'https://localhost:',
    noProxy      => ['127.0.0.1', 'localhost'],
}
```

Downside:
Recreate logic of `vagrant-proxyconf`

**Comment by ppp0** [comment]
As far as I can see we use this kind of proxying for testing VMs only. Setting and disabling proxy for all net-enabled apps is a bit awkward. That's the main reason for `vagrant-proxyconf` to exist, I imagine

**Comment by tomaszdurka** [comment]
I am not sure I understand.

My intension is to set proxy only for the tested machine (vagrant box). 
Actually currently we set this proxy for the whole box too - for all applications, etc.
I want simply to not do it by default or at least not from start, but after polipo installation/provision.
What we do now is we proxy from start, but disable it for provisioning (hacky!).

Plugin is good (gathers all the proxy types together), but it's designed for different thing. It's designed to always proxy everything within the vagrant-box. It executes itself just before provision - so intension is to proxy provisioning too (we don't want this).

We want to proxy only once polipo is there.

Imo ideal would be if plugin was executable too!
So instead of passing it as configuration only, you could also run it right after provision:
```
vagrant up/provision
vagrant proxyconf enable/disable
```
or 
```
vagrant proxyconf '{"httpProxy": "localhost:1234"}' # enables
vagrant proxyconf {}# disables
```

**Comment by tomaszdurka** [comment]
As discussed - closing for now.
